#!/bin/sh
# Start/stop script for aesdchar driver

case "$1" in
    start)
        echo "Loading aesdchar driver"
        modprobe aesdchar
        # Create device node if not created by modprobe
        if [ ! -e /dev/aesdchar ]; then
            major=$(awk "\$2==\"aesdchar\" {print \$1}" /proc/devices)
            if [ ! -z "$major" ]; then
                mknod /dev/aesdchar c $major 0
                chmod 664 /dev/aesdchar
                if grep -q '^staff:' /etc/group; then
                    chgrp staff /dev/aesdchar
                else
                    chgrp wheel /dev/aesdchar
                fi
            fi
        fi
        ;;
    stop)
        echo "Unloading aesdchar driver"
        rmmod aesdchar
        rm -f /dev/aesdchar
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
